### PR TITLE
Re-enable Linux builds

### PR DESCRIPTION
**Pull request by Marzal**
Hi, I've been doing some test[1] and I think you fixed the Linux builds a while ago. The only thing needed is to re-enable the workflow and set the variable `CPACK_DEBIAN_PACKAGE_MAINTAINER`

[1]https://github.com/Marzal/obs-multi-rtmp/actions/runs/4646300492/jobs/8222636975

Related: #189 #196 https://github.com/sorayuki/obs-multi-rtmp/issues/240#issuecomment-1455024484 #231
Fixes: #260 #213

### CODE REVIEW

**Comment by csolisr** [comment]
Don't forget to re-add `build_linux.sh`! Last version that included the file was [0.2.8.1](https://github.com/sorayuki/obs-multi-rtmp/releases/tag/0.2.8.1-OBS28).

[For your reference](https://github.com/sorayuki/obs-multi-rtmp/files/11184200/build_linux.sh.txt)

**Comment by Marzal** [comment]
> Don't forget to re-add `build_linux.sh`! Last version that included the file was [0.2.8.1](https://github.com/sorayuki/obs-multi-rtmp/releases/tag/0.2.8.1-OBS28).
> 
> [For your reference](https://github.com/sorayuki/obs-multi-rtmp/files/11184200/build_linux.sh.txt)

Good catch, if we recover the Linux CI builds, that could be a good addition, don't know if as a Wiki, article or script...

https://github.com/sorayuki/obs-multi-rtmp/blob/0.2.8.1-OBS28/ci/install_ubuntu.sh
https://github.com/sorayuki/obs-multi-rtmp/blob/0.2.8.1-OBS28/build_linux.sh

**Comment by sorayuki** [comment]
I think the old build script for Linux which is deprecated can be removed.

**Comment by Marzal** [comment]
> I think the old build script for Linux which is deprecated can be removed.

Thanks for the quick merge.

Yeah the old script would need updating to work with OBS =>29, QT6 and Ubuntu 22.04. If I someone has the time could be added to the Wiki or as documentation.

The dependencies in the deb package I think that would need also updating:
https://github.com/sorayuki/obs-multi-rtmp/blob/86bd8ea2036a31765f8bdd2656e295f5c20e48de/cmake/ObsPluginHelpers.cmake#L508
`          "obs-studio (>= 27.0.0), libqt5core5a (>= 5.9.0~beta), libqt5gui5 (>= 5.3.0), libqt5widgets5 (>= 5.7.0)"`

**Pull request merged**
