### PR TITLE
WebRTC output + protocol selector

### PR DESCRIPTION
**Pull request by lucaspontoexe**
This pull request will add support for publishing using WebRTC (WHIP) and a drop-down menu to choose a streaming protocol.

Please note that I am still learning C++ and QT. The code could definitely be better.

Bugs & things left to do:
- [X] Tabs are not updating when protocol changes. you have to save and reopen the edit widget
- [x] push-widget: choose service/output by selected protocol instead of reading it from URL
- [x] Move protocol selection functions into another file to avoid code duplication

image

for the record:
| protocol | label         | service id  | output id           |
| -------- | ------------- | ----------- | ------------------- |
| RTMP     | RTMP          | rtmp_custom | rtmp_output         |
| SRT_RIST | SRT/RIST      | rtmp_custom | ffmpeg_mpegts_muxer |
| WHIP   | WebRTC (WHIP) | whip_custom | whip_output         |

### CODE REVIEW

**Comment by sorayuki** [comment]
I got stucked in UI layout adjustment and dialog size controlled in last weekend 😣 It will be some time until I can review this
________________________________
From: Lucas Teixeira ***@***.***>
Sent: Tuesday, February 27, 2024 9:51:13 AM
To: sorayuki/obs-multi-rtmp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sorayuki/obs-multi-rtmp] [WIP] WebRTC output + protocol selector (PR #407)


This pull request will add support for publishing using WebRTC (WHIP) and a drop-down menu to choose a streaming protocol.

Please note that I am still learning C++ and QT. The code could definitely be better.

  *   Tabs are not updating when protocol changes. you have to save and reopen the edit widget
  *   I have to add some kind of std::map, so I don't have to write functions all over the place

image.png (view on web)<https://github.com/sorayuki/obs-multi-rtmp/assets/25611847/257d0d38-3985-4093-9f34-1163187d8182>

for the record:

protocol        label   service id      output id
RTMP    RTMP    rtmp_custom     rtmp_output
SRT_RIST        SRT/RIST        rtmp_custom     ffmpeg_mpegts_muxer
WebRTC  WebRTC (WHIP)   whip_custom     whip_output
________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/sorayuki/obs-multi-rtmp/pull/407

Commit Summary

  *   a840d7d<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/a840d7d87e1d617cf0e067d3835853a6832d4a8b> push-widget: add support for SRT, RIST & (possibly) HLS
  *   6a80ecf<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/6a80ecfccfab164aaa866b1f5fc2e11cd46a002c> push widget: remove hls muxer
  *   ded25a8<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/ded25a85b8dea3838ca9ab8728eec32aaa19acc6> Merge branch 'sorayuki:master' into master
  *   352ebd8<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/352ebd892fbcc3e5d775b276ce9de1e726c54a8a> edit-widget: add opus audio codec
  *   c2e9564<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/c2e956474e50b33c5c2f4a2293519e7950e97a73> use whip_output if the url starts with http
  *   8e71403<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/8e71403f4c1a50a68ea4685370be307a93fa555c> push widget: use whip_custom service if url starts with http
  *   41b21fd<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/41b21fd4794e487da83eefae2be5697c92cd5dfd> output-config: add a "protocol" field
  *   331ae75<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/331ae75c09fba0058ad337884fe3ecdcf0c348b2> output-config: back to empty string by default
  *   6510d84<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/6510d84c5088b6ebc397e890b04968df0fc895ce> edit-widget: add functions to return output & service IDs
  *   abd97d0<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/abd97d00f08ec385163d95aedad26d2583a4d517> use service ID from functions
  *   89a52ec<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/89a52ec22ba65ef500813dc0eaee2066ebbd4f04> edit-widget: save & load protocol
  *   bc35baa<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/bc35baa045cda11a9dd874b04a74c810489e074b> output-config: re-add rtmp as default
  *   b65ef2c<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/b65ef2cf580e14b6675aeb425e747982ecfd4916> push-widget: notes for later
  *   1157cf9<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/1157cf9ed82522ebf83ed217844257b0b37937a6> edit-widget: add the protocol selector combo box
  *   1b0da1a<https://github.com/sorayuki/obs-multi-rtmp/pull/407/commits/1b0da1a193858da30cdc5f79bf96c576be7e60ef> createprotocolselector2 -> createprotocolselector

File Changes

(4 files<https://github.com/sorayuki/obs-multi-rtmp/pull/407/files>)

  *   M src/edit-widget.cpp<https://github.com/sorayuki/obs-multi-rtmp/pull/407/files#diff-c4afb8a9a8ce11d3ec4599483070d52afcf9b2aa12c68d3f1e4349089ca31ea7> (88)
  *   M src/output-config.cpp<https://github.com/sorayuki/obs-multi-rtmp/pull/407/files#diff-1767a602f4a1ca3300b5b2f1e81413695c57bffbe5553bd8f8aa387c91a773b6> (2)
  *   M src/output-config.h<https://github.com/sorayuki/obs-multi-rtmp/pull/407/files#diff-178438e20c71041f7104d36caaed9ca3554b8b2a95332af09e89a2ca469fb9ad> (1)
  *   M src/push-widget.cpp<https://github.com/sorayuki/obs-multi-rtmp/pull/407/files#diff-9cb4052d9005604fdb715b39e2a8decbaed1b233bba247b2203958a1680d635c> (10)

Patch Links:

  *   https://github.com/sorayuki/obs-multi-rtmp/pull/407.patch
  *   https://github.com/sorayuki/obs-multi-rtmp/pull/407.diff

**Comment by lucaspontoexe** [comment]
No problem, take your time! I haven't finished yet.

**Comment by lucaspontoexe** [comment]
Ready for review! I would appreciate your feedback.

**Comment by sorayuki** [comment]
I made a little change to the protocol information code and edit widget layout.

**Pull request merged**
